apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: nginx:alpine

---

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod2
spec:
  containers:
  - name: myapp-container
    image: nginx:alpine
